# Generated by Django 3.1.2 on 2020-11-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_like_test'),
        ('main_app', '0028_auto_20201106_0010'),
    ]

    operations = [
    ]
