# Generated by Django 3.1.4 on 2020-12-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_merge_20201106_0400'),
        ('main_app', '0029_merge_20201106_0719'),
    ]

    operations = [
    ]
